function todayHTML(){
  let d=today(),as=A.filter(a=>a.date===d&&!['cancelled','missed'].includes(a.status)).sort((a,b)=>a.time.localeCompare(b.time)),now=new Date(),nm=now.getHours()*60+now.getMinutes(),next=as.find(a=>a.status!=='done'&&tmin(a.time)+P[a.procedure].min>=nm)||as.find(a=>a.status!=='done');
  let due=returns().filter(r=>r.notify<=d&&!future(r)).sort((a,b)=>a.due.localeCompare(b.due));
  let w=weekData(obj(d).getDay()===0?add(d,1):wstart(d)),gaps=segments(d).filter(s=>s.k==='free'&&s.e-s.s>=50).slice(0,3);
  let old=returns().filter(r=>r.due<d&&!future(r)).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4);
  let share=weeklyShareText(w);
  let state=next?`<div class="today-summary"><div class="state"><i class="state-dot ${next.status==='confirmed'?'ok':''}"></i><div><strong>Próximo: ${next.time} · ${next.client}</strong><span>${P[next.procedure].name} · ${money(P[next.procedure].price)}</span></div></div><button class="link-action" onclick="openAppt('${next.id}')">Abrir →</button></div>`:`<div class="today-summary"><div class="state"><i class="state-dot ok"></i><div><strong>Sem próximo atendimento pendente</strong><span>${as.length} atendimento${as.length!==1?'s':''} registrado${as.length!==1?'s':''} hoje · ${due.length} contato${due.length!==1?'s':''} para fazer</span></div></div></div>`;
  return `<div class="stack">${state}
    <section class="section"><div class="section-head"><div><div class="eyebrow">AÇÃO AGORA</div><h2>Contatar hoje</h2></div><span class="section-count">${due.length}</span></div><div class="divider-list">${due.map(todayContactRow).join('')||'<div class="empty">Nenhuma cliente precisa de contato hoje.</div>'}</div></section>
    <section class="section"><div class="section-head"><div><div class="eyebrow">AGENDA</div><h2>Hoje</h2></div><button class="link-action" onclick="sel=today();view='day';go('agenda')">Agenda completa →</button></div><div class="divider-list">${as.map(todayApptRow).join('')||'<div class="empty">Nenhum atendimento agendado.</div>'}</div>${gaps.length?`<div class="free-line">Janelas disponíveis: ${gaps.map(g=>`${mt(g.s)}–${mt(g.e)}`).join(' · ')}</div>`:''}</section>
    <section class="section"><div class="section-head"><div><div class="eyebrow">SEMANA</div><h2>${obj(today()).getDay()===0?'Relatório de domingo':'Resumo operacional'}</h2><p>Agenda, receita prevista, retornos e oportunidades.</p></div><a class="icon" aria-label="Compartilhar relatório" target="_blank" href="https://wa.me/?text=${encodeURIComponent(share)}">${ICONS.share}</a></div><div class="week-brief"><div class="brief-stat"><strong>${w.apps.length}</strong><span>agendados</span></div><div class="brief-stat"><strong>${money(w.rev)}</strong><span>receita prevista</span></div><div class="brief-stat"><strong>${w.rs.length}</strong><span>contatos da semana</span></div></div>
      <div>${w.daysFree.sort((a,b)=>b.minutes-a.minutes).slice(0,2).map(x=>`<div class="report-line"><div><strong>${weekday(x.date).toUpperCase()} ${fmt(x.date,{day:'2-digit',month:'short'})}</strong><span>${x.minutes>=120?`${Math.floor(x.minutes/60)}h${x.minutes%60?String(x.minutes%60).padStart(2,'0'):''} livres`:`${x.minutes} min livres`} · ${x.gaps.slice(0,2).map(g=>`${mt(g.s)}–${mt(g.e)}`).join(' / ')||'sem janela'}</span></div><button class="link-action" onclick="sel='${x.date}';view='day';go('agenda')">Abrir</button></div>`).join('')}</div>
      ${old.length?`<div class="free-line">Clientes antigas sugeridas: ${old.map(r=>r.name.split(' ')[0]).join(', ')}.</div>`:''}
    </section>
  </div>`
}
function todayContactRow(r){let msg=encodeURIComponent(`Oi, ${r.name.split(' ')[0]}! Passando para organizar seu próximo horário na Esmalta. 💅`);return `<div class="action-row"><div class="avatar">${ini(r.name)}</div><div class="action-main"><strong>${r.name}</strong><span>${r.type==='return'?P[r.suggest].name:'Oportunidade de reativação'}</span><small>${r.due<today()?`${days(r.due,today())} dias atrasada`:r.type==='react'?`${days(r.lastVisit,today())} dias sem retornar`:'Retorno ideal hoje'}</small></div><div class="row-actions">${r.phone?`<a class="wa" target="_blank" href="https://wa.me/55${r.phone}?text=${msg}">${ICONS.whatsapp}<span>WhatsApp</span></a>`:""}<button class="mini" onclick="scheduleReturn('${r.id}')">Agendar</button></div></div>`}
function todayApptRow(a){return `<button class="today-appt" onclick="openAppt('${a.id}')"><div class="time">${a.time}</div><div><strong><i class="status-dot ${a.status}"></i>${a.client}</strong><span>${P[a.procedure].name} · ${statusLabel(a.status)}</span></div><b class="chev">›</b></button>`}
function weeklyShareText(w){let contacts=w.rs.map(r=>`${r.name} (${r.type==='return'?P[r.suggest].name:'reativação'})`).join(', ')||'nenhum';let frees=w.daysFree.sort((a,b)=>b.minutes-a.minutes).slice(0,3).map(x=>`${weekday(x.date)} ${fmt(x.date,{day:'2-digit'})}: ${x.gaps.map(g=>`${mt(g.s)}–${mt(g.e)}`).join('/')||'sem janelas'}`).join('\n');let old=returns().filter(r=>r.due<today()&&!future(r)).slice(0,5).map(r=>r.name).join(', ')||'nenhuma';return `Relatório Esmalta — ${fmt(w.start)} a ${fmt(w.end)}\n\nAgenda: ${w.apps.length} atendimentos\nReceita prevista: ${money(w.rev)}\n\nClientes para contato: ${contacts}\n\nMelhores janelas:\n${frees}\n\nClientes antigas sugeridas: ${old}`}

function agendaHTML(){return `<div class="agenda"><div class="toolbar"><div class="views"><button class="${view==='day'?'active':''}" onclick="view='day';render()">Dia</button><button class="${view==='week'?'active':''}" onclick="view='week';render()">Semana</button><button class="${view==='month'?'active':''}" onclick="view='month';render()">Mês</button></div><div class="date-nav"><button class="icon" aria-label="Anterior" onclick="shift(-1)">${ICONS.left}</button><button class="date-label" onclick="sel=today();view='day';render()"><strong>${view==='month'?fmt(sel,{month:'long',year:'numeric'}):view==='week'?'Semana de '+fmt(wstart(sel)):long(sel)}</strong><small>${sel===today()?'Hoje':'Toque para voltar a hoje'}</small></button><button class="icon" aria-label="Próximo" onclick="shift(1)">${ICONS.right}</button></div></div>${view==='day'?dayHTML():view==='week'?weekHTML():monthHTML()}</div>`}
function shift(n){sel=view==='day'?add(sel,n):view==='week'?add(sel,n*7):monthAdd(sel,n);render()}
function dayHTML(){let r=work(sel),as=A.filter(a=>a.date===sel&&!['cancelled','missed'].includes(a.status));if(!r)return `<section class="day"><div class="empty" style="text-align:center;padding:56px 0">Domingo · sem atendimento.</div></section>`;return `<section class="day"><div class="dayhead"><div><div class="eyebrow">${sel===today()?'HOJE':'AGENDA DO DIA'}</div><h2>${as.length} atendimento${as.length!==1?'s':''}</h2></div><span>${mt(r[0])}–${mt(r[1])}</span></div><div class="timeline">${segments(sel).map(s=>s.k==='appt'?dayAppt(s):dayFree(s)).join('')}</div></section>`}
function dayAppt(s){let a=s.a;return `<button class="appt ${a.status}" onclick="openAppt('${a.id}')"><div class="times"><strong>${a.time}</strong><span>${mt(s.e)}</span></div><i class="bar"></i><div class="info"><strong>${a.client}</strong><span>${P[a.procedure].name} · ${money(P[a.procedure].price)}</span><small>${statusLabel(a.status)} · ${P[a.procedure].min} min</small></div><b class="chev">›</b></button>`}
function dayFree(s){let dur=s.e-s.s,disabled=dur<50;return `<button class="free ${disabled?'short':''}" ${disabled?'disabled':''} onclick="openNew('${sel}','${mt(s.s)}','${dur>=120?'alongamento':dur>=80?'manutencao':'peOuMao'}')"><span>${mt(s.s)}</span><div><strong>${disabled?'Intervalo':'+ Agendar neste horário'}</strong><small>${dur} min disponíveis${!disabled?` · até ${mt(s.e)}`:''}</small></div>${!disabled?'<b class="plus-inline">+</b>':''}</button>`}
function weekHTML(){let st=wstart(sel),ds=Array.from({length:6},(_,i)=>add(st,i));return `<section class="week-summary">${ds.map(d=>{let as=A.filter(a=>a.date===d&&!['cancelled','missed'].includes(a.status)).sort((a,b)=>a.time.localeCompare(b.time)),r=work(d),book=as.reduce((s,a)=>s+P[a.procedure].min,0),cap=r?r[1]-r[0]:1,pct=Math.min(100,Math.round(book/cap*100)),g=segments(d).filter(s=>s.k==='free'&&s.e-s.s>=50);return `<article class="week-day ${d===today()?'today':''} ${pct>70?'busy':''}"><button class="whead" onclick="sel='${d}';view='day';render()"><span>${weekday(d)}</span><strong>${obj(d).getDate()}</strong></button><div class="occupancy"><i style="width:${pct}%"></i></div><div class="wmeta">${as.length} atend. · ${pct}% ocupado</div><div class="week-events">${as.slice(0,4).map(a=>`<button class="week-event" onclick="openAppt('${a.id}')"><b>${a.time}</b><span>${a.client.split(' ')[0]}</span></button>`).join('')||'<div class="empty">Dia livre</div>'}</div><button class="week-free" onclick="sel='${d}';view='day';render()">${g.length?`${g.length} janela${g.length>1?'s':''} livre${g.length>1?'s':''} →`:'Ver dia →'}</button></article>`}).join('')}</section>`}
function monthHTML(){let d=obj(sel),y=d.getFullYear(),m=d.getMonth(),f=new Date(y,m,1,12),st=new Date(f);st.setDate(f.getDate()-f.getDay());let cells=Array.from({length:42},(_,i)=>{let x=new Date(st);x.setDate(st.getDate()+i);return iso(x)});return `<section class="month"><div class="weekdays">${['D','S','T','Q','Q','S','S'].map(x=>'<span>'+x+'</span>').join('')}</div><div class="monthgrid">${cells.map(x=>{let inside=obj(x).getMonth()===m,as=A.filter(a=>a.date===x&&!['cancelled','missed'].includes(a.status)),r=work(x),book=as.reduce((s,a)=>s+P[a.procedure].min,0),cap=r?r[1]-r[0]:1,l=!r?'closed':book/cap>.7?'busy':book/cap>.25?'medium':'light';return `<button class="mday ${!inside?'out':''} ${x===today()?'today':''} ${l}" onclick="sel='${x}';view='day';render()"><span>${obj(x).getDate()}</span>${as.length?'<b>'+as.length+'</b>':''}<i></i></button>`}).join('')}</div><div class="legend"><span><i></i>livre</span><span><i class="med"></i>parcial</span><span><i class="busy"></i>ocupado</span></div></section>`}

function returnsHTML(){let rs=returns().filter(r=>!future(r)).sort((a,b)=>a.notify.localeCompare(b.notify)),technical=rs.filter(r=>r.type==='return'),react=rs.filter(r=>r.type==='react');return `<div><section class="return-group"><div class="section-head"><div><div class="eyebrow">RETORNO TÉCNICO</div><h2>Manutenção</h2><p>Prioridade por atraso ou proximidade do retorno.</p></div><span class="section-count">${technical.length}</span></div>${technical.map(retCard).join('')||'<div class="empty">Nenhum retorno técnico pendente.</div>'}</section><section class="return-group"><div class="section-head"><div><div class="eyebrow">REATIVAÇÃO</div><h2>Clientes para recuperar</h2><p>Tradicionais e clientes sem novo agendamento.</p></div><span class="section-count">${react.length}</span></div>${react.map(retCard).join('')||'<div class="empty">Nenhuma reativação sugerida.</div>'}</section></div>`}
function retCard(r){let msg=encodeURIComponent(`Oi, ${r.name.split(' ')[0]}! Passando para organizar seu próximo horário na Esmalta. 💅`),late=r.due<today();return `<div class="return-card"><div class="avatar">${ini(r.name)}</div><div><strong>${r.name}</strong><span>${r.type==='return'?`Próximo: ${P[r.suggest].name} · ideal ${fmt(r.due)}`:`Última visita ${fmt(r.lastVisit)} · ${days(r.lastVisit,today())} dias`}</span><small class="${late?'':'future'}">${late?`${days(r.due,today())} dias atrasada`:ageText(r)}</small><span class="type-chip">${r.type==='return'?'Retorno técnico':'Reativação'}</span></div><div class="actions">${r.phone?`<a class="wa" title="WhatsApp" target="_blank" href="https://wa.me/55${r.phone}?text=${msg}">${ICONS.whatsapp}</a>`:""}<button class="mini" onclick="scheduleReturn('${r.id}')">Agendar</button></div></div>`}

function clientsHTML(){return `<div class="clients-wrap"><div class="search">${ICONS.search}<input id="q" placeholder="Buscar por nome ou WhatsApp" oninput="filterClients(this.value)"></div><div id="clientList">${clientRows(C)}</div></div>`}
function clientRows(cs){return cs.slice().sort((a,b)=>(b.lastVisit||'').localeCompare(a.lastVisit||'')).map(c=>{let r=returns().find(x=>x.phone===c.phone),f=A.find(a=>a.phone===c.phone&&a.date>=today()&&!['cancelled','missed'].includes(a.status)),state=f?`Agendada ${fmt(f.date)}`:r?(r.due<today()?`${days(r.due,today())} dias atrasada`:`Ação ${fmt(r.notify)}`):'Sem próxima ação';return `<button class="client" onclick="openClient('${c.id}')"><div class="avatar">${ini(c.name)}</div><div><strong>${c.name}</strong><span class="sub">Última visita ${fmt(c.lastVisit)} · ${c.visits||0} atendimentos</span></div><div class="client-state ${r&&r.due<today()&&!f?'late':''}">${state}<br><span class="chev">›</span></div></button>`}).join('')}
function filterClients(q){clientList.innerHTML=clientRows(C.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())||c.phone.includes(q)))}

function settingsHTML(){return `<section class="settings"><div class="section-head"><div><div class="eyebrow">CONFIGURAÇÕES</div><h2>Procedimentos</h2><p>Preço, duração e regra de retorno.</p></div></div><div class="proc-list">${Object.entries(P).map(([id,p])=>`<div class="proc"><div><strong>${p.name}</strong><span>${money(p.price)} · ${Math.floor(p.min/60)?Math.floor(p.min/60)+'h':''}${p.min%60?String(p.min%60).padStart(2,'0'):''}</span></div><small>${p.days?`Retorno ${p.days} dias${p.next?' → '+P[p.next].name:''}`:`Reativar em ${p.react} dias`}</small></div>`).join('')}</div><div class="schedule-config"><strong>Horário de atendimento</strong><span>Segunda a sexta · 08:00–17:30<br>Sábado · 08:00–18:00<br>Sem pausa fixa de almoço.</span></div></section>`}

function splitPhone(p){p=String(p||'').replace(/\D/g,'');if(p.length>10)return[p.slice(0,2),p.slice(2)];return['77',p];}
function openNew(date=(tab==='agenda'?sel:today()),time='08:00',proc='manutencao',client='',phone='',edit=''){
 overlay.innerHTML=`<div class="back" onclick="if(event.target===this)closeSheet()"><section class="sheet"><div class="grab"></div><div class="sheettop"><h2>${edit?'Reagendar':'Novo agendamento'}</h2><button class="icon" onclick="closeSheet()">${ICONS.close}</button></div><div class="form"><label>Cliente<input id="fc" list="cl" placeholder="Busque ou digite o nome" value="${client}"><datalist id="cl">${C.map(c=>`<option value="${c.name}">`).join('')}</datalist></label><div id="existingClient" class="existing-client"></div><div class="formrow"><label style="max-width:90px">DDD<input id="fdd" inputmode="numeric" placeholder="77" value="${splitPhone(phone)[0]}"></label><label>WhatsApp (opcional)<input id="fp" inputmode="numeric" placeholder="99999-9999" value="${splitPhone(phone)[1]}"></label></div><label>Procedimento<select id="fproc" onchange="formSummary()">${Object.entries(P).map(([id,p])=>`<option value="${id}" ${id===proc?'selected':''}>${p.name}</option>`).join('')}</select></label><div class="formrow"><label>Data<input id="fd" type="date" value="${date}"></label><label>Horário<input id="ft" type="time" value="${time}"></label></div><div class="summary" id="fs"></div><button class="primary" onclick="saveBooking('${edit}')">${edit?'Salvar novo horário':'Confirmar agendamento'}</button></div></section></div>`;
 const syncClient=()=>{let c=C.find(x=>x.name.toLowerCase()===fc.value.trim().toLowerCase());if(c){fp.value=c.phone;existingClient.textContent=`Cliente existente · ${c.visits||0} atendimentos · última ${fmt(c.lastVisit)}`;existingClient.classList.add('show')}else existingClient.classList.remove('show')};fc.addEventListener('input',syncClient);syncClient();formSummary()
}
function formSummary(){let p=P[fproc.value];fs.innerHTML=`<span>${p.min} min</span><span>${money(p.price)}</span><span>${p.days?'retorno em '+p.days+' dias':'reativação em '+p.react+' dias'}</span>`}
function saveBooking(edit){let ddd=String(fdd.value||'').replace(/\D/g,''),num=String(fp.value||'').replace(/\D/g,''),phone=(ddd||num)?(ddd.padStart(2,'0')+num):'';let f={client:fc.value.trim(),phone:phone,date:fd.value,time:ft.value,procedure:fproc.value};if(!f.client)return toastMsg('Informe o nome da cliente.');if(f.phone&&f.phone.length<10)return toastMsg('WhatsApp incompleto. Confira o DDD e o número.');let e=valid(f,edit);if(e)return toastMsg(e);if(edit)A=A.map(a=>String(a.id)===String(edit)?{...a,...f}:a);else{A.push({id:Date.now(),...f,status:'scheduled'});if(f.phone&&!C.some(c=>c.phone&&c.phone===f.phone))C.push({id:Date.now()+1,name:f.client,phone:f.phone,lastProcedure:f.procedure,visits:0,spent:0})}save();sel=f.date;view='day';tab='agenda';closeSheet();toastMsg(edit?'Agendamento atualizado.':'Agendamento criado.');render()}

function openAppt(id){let a=A.find(x=>String(x.id)===String(id));if(!a||!P[a.procedure])return toastMsg("Atendimento não encontrado. Recarregue a página.");let p=P[a.procedure],msg=encodeURIComponent(`Oi, ${a.client.split(' ')[0]}! Confirmando seu horário na Esmalta: ${fmt(a.date)} às ${a.time}. 💅`);overlay.innerHTML=`<div class="back" onclick="if(event.target===this)closeSheet()"><section class="sheet"><div class="grab"></div><div class="sheettop"><span class="eyebrow">ATENDIMENTO</span><button class="icon" onclick="closeSheet()">${ICONS.close}</button></div><div class="apptdetail"><div class="eyebrow">${long(a.date)}</div><h2>${a.client}</h2><p>${a.time}–${mt(tmin(a.time)+p.min)} · ${p.name}</p><strong class="price">${money(p.price)}</strong><span class="appt-status"><i class="status-dot ${a.status}"></i>${statusLabel(a.status)}</span></div><div class="action-primary">${a.status!=='done'?`<button onclick="statusAppt('${id}','done')">Concluir atendimento</button>`:''}${a.status==='scheduled'?`<button class="confirm" onclick="statusAppt('${id}','confirmed')">Confirmar presença</button>`:''}</div><div class="action-secondary">${a.phone?`<a target="_blank" href="https://wa.me/55${a.phone}?text=${msg}">WhatsApp</a>`:""}<button onclick="rebook('${id}')">Reagendar</button>${!['done','cancelled','missed'].includes(a.status)?`<button class="danger" onclick="statusAppt('${id}','missed')">Faltou</button>`:''}${!['done','cancelled','missed'].includes(a.status)?`<button class="danger" onclick="statusAppt('${id}','cancelled')">Cancelar</button>`:''}</div></section></div>`}
function rebook(id){let a=A.find(x=>String(x.id)===String(id));if(!a)return toastMsg("Atendimento não encontrado. Recarregue a página.");openNew(a.date,a.time,a.procedure,a.client,a.phone,id)}
function statusAppt(id,s){let a=A.find(x=>String(x.id)===String(id));if(!a)return toastMsg("Atendimento não encontrado. Recarregue a página.");a.status=s;if(s==='done'){let p=P[a.procedure],due=p.days?add(a.date,p.days):null,c=C.find(x=>x.phone===a.phone);if(c){c.name=a.client;c.lastProcedure=a.procedure;c.lastVisit=a.date;c.nextDue=due;c.visits=(c.visits||0)+1;c.spent=(c.spent||0)+p.price}else C.push({id:Date.now(),name:a.client,phone:a.phone,lastProcedure:a.procedure,lastVisit:a.date,nextDue:due,visits:1,spent:p.price});toastMsg(p.days?'Atendimento concluído · retorno recomendado '+fmt(due)+'.':'Atendimento concluído · cliente entrou na régua de reativação.')}else toastMsg(s==='confirmed'?'Atendimento confirmado.':s==='missed'?'Falta registrada.':'Atendimento cancelado.');save();closeSheet();render()}
function scheduleReturn(id){let r=returns().find(x=>String(x.id)===String(id));if(!r)return toastMsg("Cliente não encontrado. Recarregue a página.");let start=r.due<today()?today():r.due,s=firstSlot(start,r.suggest);openNew(s?.date||today(),s?.time||'08:00',r.suggest,r.name,r.phone)}
function openClient(id){
  let c=C.find(x=>String(x.id)===String(id));if(!c)return toastMsg("Cliente não encontrado. Recarregue a página.");let escName=String(c.name||"").split(String.fromCharCode(39)).join(String.fromCharCode(92,39)),r=returns().find(x=>x.phone===c.phone),hist=clientHistory(c.phone),msg=encodeURIComponent(`Oi, ${c.name.split(' ')[0]}! 💅`);
  let action='';
  if(r){
    if(r.type==='return') action=`${P[r.suggest].name} ${r.due<today()?`· ${days(r.due,today())} dias atrasada`:`· ${fmt(r.due)}`}`;
    else action=`Reativar · ${days(r.lastVisit,today())} dias sem retornar`;
  }
  overlay.innerHTML=`<div class="back" onclick="if(event.target===this)closeSheet()"><section class="sheet"><div class="grab"></div><div class="sheettop"><span class="eyebrow">CLIENTE</span><button class="icon" onclick="closeSheet()">${ICONS.close}</button></div><div class="profile"><div class="profile-head"><div class="avatar">${ini(c.name)}</div><div><h2>${c.name}</h2><span>${c.phone}</span></div></div><div class="profilebuttons">${c.phone?`<a target="_blank" href="https://wa.me/55${c.phone}?text=${msg}">WhatsApp</a>`:""}<button onclick="closeSheet();openNew('${r?.due||today()}','08:00','${r?.suggest||c.lastProcedure||'manutencao'}','${escName}','${c.phone}')">">Agendar</button></div><div class="profile-stats"><div class="profile-stat"><strong>${c.visits||0}</strong><span>atendimentos</span></div><div class="profile-stat"><strong>${fmt(c.lastVisit)}</strong><span>última visita</span></div><div class="profile-stat"><strong>${money(c.spent||0)}</strong><span>total gasto</span></div></div>${r?`<div class="next-action">Próxima ação · <strong>${action}</strong></div>`:''}<div class="history"><h3>Histórico</h3>${hist.length?hist.map(a=>`<div class="history-item"><time>${fmt(a.date)}</time><div><strong>${P[a.procedure].name}</strong><span>${a.time} · ${P[a.procedure].min} min</span></div><strong>${money(P[a.procedure].price)}</strong></div>`).join(''):'<div class="empty">Nenhum atendimento concluído registrado.</div>'}</div></div></section></div>`;
}
render();